### ISSUE TITLE
[Bug]框架{{unicode(a)}}参数过滤器BUG.

### ISSUE THREAD

**Issue by wjf0214** [a76yyyy/qiandao#15]
**Describe the bug**
框架{{unicode(a)}}参数过滤器BUG.

**To Reproduce**
当res为变量的时候。{{unicode(res)}}没有转换。把res直接输出了。
但是我把res换着对应的字符串值就可以。

**Expected behavior**
当{{unicode(res)}}方式使用的时候，应该正常转换输出。而不是输出res原值。

**Screenshots**
![6)I`V8C7H}A910$0X }J~X](https://user-images.githubusercontent.com/23102821/133949692-2a299317-68e8-4a1d-a2b4-965d3225ab12.png)

![Q`HR`ID UE%Z79 6VT9EBYH](https://user-images.githubusercontent.com/23102821/133949506-0b843a8b-2623-421c-9dc7-bfe6690e0868.png)

**Version**
Docker镜像20210917版本。

**Comment by a76yyyy** [comment]
已修复，请使用docker内源码更新方式更新框架并重启容器

**Comment by wjf0214** [comment]
> 已修复，请使用docker内源码更新方式更新框架并重启容器

更新完后报错。错误信息为：
```
[E 210928 18:00:25 web:1789] Uncaught exception POST /har/test (xxx.xxx.xxx.xxx)

    HTTPServerRequest(protocol='http', host='xxxx', method='POST', uri='/har/test', version='HTTP/1.0', remote_ip='xxx.xxx.xxx.xxx')

    Traceback (most recent call last):

      File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute

        result = await result

      File "/usr/src/app/web/handlers/har.py", line 74, in post

        ret = await gen.convert_yielded(self.fetcher.fetch(data))

      File "/usr/src/app/libs/fetcher.py", line 465, in fetch

        rule, env, response = await gen.convert_yielded(self.build_response(obj, proxy, CURL_ENCODING, CURL_CONTENT_LENGTH))

      File "/usr/src/app/libs/fetcher.py", line 422, in build_response

        response =  await gen.convert_yielded(self.client.fetch(req))

      File "/usr/local/lib/python3.8/site-packages/tornado/curl_httpclient.py", line 234, in _process_queue

        self._curl_setup_request(

      File "/usr/local/lib/python3.8/site-packages/tornado/curl_httpclient.py", line 333, in _curl_setup_request

        curl.setopt(pycurl.URL, native_str(request.url))

    UnicodeEncodeError: 'ascii' codec can't encode characters in position 106-122: ordinal not in range(128)

[E 210928 18:00:25 web:1789] Uncaught exception POST /har/test (xxx.xxx.xxx.xxx)

    HTTPServerRequest(protocol='http', host='xxx', method='POST', uri='/har/test', version='HTTP/1.0', remote_ip='xxx.xxx.xxx.xxx')

    Traceback (most recent call last):

      File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute

        result = await result

      File "/usr/src/app/web/handlers/har.py", line 74, in post

        ret = await gen.convert_yielded(self.fetcher.fetch(data))

      File "/usr/src/app/libs/fetcher.py", line 465, in fetch

        rule, env, response = await gen.convert_yielded(self.build_response(obj, proxy, CURL_ENCODING, CURL_CONTENT_LENGTH))

      File "/usr/src/app/libs/fetcher.py", line 422, in build_response

        response =  await gen.convert_yielded(self.client.fetch(req))

      File "/usr/local/lib/python3.8/site-packages/tornado/curl_httpclient.py", line 234, in _process_queue

        self._curl_setup_request(

      File "/usr/local/lib/python3.8/site-packages/tornado/curl_httpclient.py", line 333, in _curl_setup_request

        curl.setopt(pycurl.URL, native_str(request.url))
```

**Comment by a76yyyy** [comment]
bug修复后请确保url内容的中文被urlencode转码

**right**
![image](https://user-images.githubusercontent.com/56478790/135079130-09beedc2-71b0-4600-b0d5-3199c026aec2.png)
**error1**
![image](https://user-images.githubusercontent.com/56478790/135079226-7ced348d-87d0-463f-80bb-8eb0f8b8fbcc.png)
**error2**
![image](https://user-images.githubusercontent.com/56478790/135079660-fcc0da5f-7a1f-4247-98e4-89b63e3a802f.png)

**Comment by wjf0214** [comment]
这样之后好了！
